# Site settings
name: BeReal
email: zengchengjieit@163.com
author: zengchengjie
url: https://github.com/zengchengjie
resume_site: http://zengchengjie.github.io/
github: https://github.com/zengchengjie
baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: 曾成洁;个人博客;别说话就是干
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zengchengjie
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

